included: # paths to include during linting. `--path` is ignored if present.
  - Lab/Lab/Sources
  - ./Packages
  - ../SharedPackages

excluded:
  - ./Packages/*/.swiftpm
  - ./Packages/*/DerivedData
  - ./SharedPackages/*/.swiftpm
  - ../SharedPackages/*/DerivedData

disabled_rules:
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - implicit_getter

# Enabled opt rules

opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - cyclomatic_complexity
  - discouraged_assert
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - indentation_width
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - yoda_condition

# Customizng opt rules

cyclomatic_complexity:
  warning: 10
  error: 50
  ignores_case_statements: true

enum_case_associated_values_count:
  warning: 4
  error: 5

type_body_length:
  warning: 600
  error: 1000

file_length:
  warning: 600
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 5
  error: 6

indentation_width:
  indentation_width: 2
  include_comments: false

identifier_name:
  min_length: 3
  excluded:
    - on
    - id
    - ID
    - vc
    - vm
    - i
    - x
    - y
  allowed_symbols:
    - _

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 180
  error: 181
  ignores_urls: true
  ignores_comments: true

type_name:
  excluded:
    - ID
  allowed_symbols:
    - _

nesting:
  type_level: 2

# Custom rules

custom_rules:

  disable_print:
    name: "print usage"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "Use logging API instead."
    severity: warning
